---
grails:
    profile: web
    codegen:
        defaultPackage: church
    gorm:
        reactor:
            events: false
    # cors:
    #     enabled: true
    #     mappings:
    #         "/**":
    #             allowedOrigins: ["http://localhost:4200"]
    #             allowedMethods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    #             allowedHeaders: ["Authorization", "Content-Type", "X-Requested-With", "Accept"]
    #             allowCredentials: true
    plugin:
        springsecurity:
            enabled: false
        #         cors:
        #             enabled: true
        #             allowedOrigins: "http://localhost:4200"
        #             allowedMethods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
        #             allowedHeaders: ["Authorization", "Content-Type", "X-Requested-With", "Accept"]
        #             allowCredentials: true
    cors:
        enabled: true
        mapping: "/**"
        allowedOrigins: "http://localhost:4200"
        allowedMethods: "GET, POST, PUT, DELETE, OPTIONS"
        allowedHeaders: "*"
        allowCredentials: true
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    jmx:
        unique-names: true
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false
    devtools:
        restart:
            additional-exclude:
                - '*.gsp'
                - '**/*.gsp'
                - '*.gson'
                - '**/*.gson'
                - 'logback.groovy'
                - '*.properties'
management:
    endpoints:
        enabled-by-default: false

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlet: html
                taglib: none
                staticparts: none
management:
    endpoints:
        jmx:
            unique-names: true

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
dataSource:
    pooled: true
    jmxExport: true
    # driverClassName: org.h2.Driver
    # username: sa
    # password: ''
    driverClassName: com.mysql.cj.jdbc.Driver
    username: grails_user
    password: RedM1234
    dialect: org.hibernate.dialect.MySQL8Dialect
    url: jdbc:mysql://localhost:3306/church_db?useSSL=false&serverTimezone=UTC

environments:
    development:
        dataSource:
            dbCreate: update
            url: jdbc:mysql://localhost:3306/church_db?useSSL=false&serverTimezone=UTC
    test:
        dataSource:
            dbCreate: update
            url: jdbc:mysql://127.0.0.1:3306/church_db_test?useSSL=false
    production:
        dataSource:
            dbCreate: none
            url: jdbc:mysql://localhost:3306/church_db?useSSL=true&serverTimezone=UTC
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
server:
    servlet:
        context-path: /church